apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: spotify-prod
data: 
  PORT: '5000'
  MONGO_URI: mongodb+srv://shoaibkhan31656_db_user:GbixHQp9juqHkqbl@cluster0.1hq8ljm.mongodb.net/?appName=Cluster0
  JWT_SECRET: shoyabkhan1234
